### ISSUE TITLE
Make models

### ISSUE THREAD

**Issue by dns2316** [dns2316/Django-API#4]
Was make follow models: user, movie.
Database: SQLite3.

**Comment by kdelinx** [comment]
You have some needed fixes:
   model Movie:
       - created_at -> auto_now_add=True
       - updated_at -> auto_now=True
       - url -> models.UrlField(max_length=255)
       - description -> models.TextField()
      p.s. CharField - max value = 255, if you want more, use a textfield

**Comment by kdelinx** [comment]
For model User, read this manual - https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#a-full-example
and after that, you need move logic with user to another application.
